### ISSUE TITLE
使用ISFJ的数据微调模型回答自己是ISTJ

### ISSUE THREAD

**Issue by mst272** [PKU-YuanGroup/Machine-Mindset#4]
请问你们出现过这种情况吗，我使用deepseek、qwen、phi-3等进行你们数据readme里提示的ISFJ数据构成进行lora微调，模型会回答自己是ISTJ或者直接回答不出自己是什么类型的mbti。请问你们遇到过吗？

**Comment by Lyu6PosHao** [comment]
您好，我们在huggingface上更新了self-awareness数据集，对应原论文中的self-awareness部分。该数据集应该能解决您的问题。
